2025-06-05 14:06:39,772 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-06-05 14:06:39,775 - WARNING - Bad Request: /
2025-06-05 14:06:40,880 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-06-05 14:06:40,881 - WARNING - Bad Request: /
2025-06-05 14:06:40,934 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-06-05 14:06:40,935 - WARNING - Bad Request: /favicon.ico
2025-06-05 14:06:46,313 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-06-05 14:06:46,315 - WARNING - Bad Request: /
2025-06-05 14:06:46,330 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-06-05 14:06:46,331 - WARNING - Bad Request: /favicon.ico
2025-06-05 14:11:01,294 - INFO - /home/steve/Templates/django/test_project/settings.py changed, reloading.
