2025-04-27 16:44:03,183 - WARNING - Not Found: /favicon.ico
2025-04-27 16:50:02,234 - INFO - /home/steve/Templates/django/blog/admin.py changed, reloading.
2025-04-27 17:04:26,080 - INFO - /home/steve/Templates/django/blog/models.py changed, reloading.
2025-04-27 17:07:23,304 - ERROR - Internal Server Error: /admin/blog/comment/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: blog_comment.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: blog_comment.email
2025-04-27 17:18:35,454 - INFO - /home/steve/Templates/django/blog/models.py changed, reloading.
2025-04-27 17:48:15,921 - ERROR - Internal Server Error: /articles/everything-rumored-for-the-2025-apple-watch-series-11/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 62, in article_detail
    'form': form
            ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
2025-04-27 17:53:25,232 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-27 17:53:35,249 - ERROR - Internal Server Error: /articles/everything-rumored-for-the-2025-apple-watch-series-11/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 62, in article_detail
    'form': form
            ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
2025-04-27 17:53:36,821 - ERROR - Internal Server Error: /articles/everything-rumored-for-the-2025-apple-watch-series-11/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 62, in article_detail
    'form': form
            ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
2025-04-27 21:30:20,021 - ERROR - Internal Server Error: /articles/everything-rumored-for-the-2025-apple-watch-series-11/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 62, in article_detail
    'form': form
            ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
2025-04-27 21:30:20,073 - WARNING - Not Found: /favicon.ico
2025-04-27 21:37:51,941 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-27 21:55:16,182 - INFO - /home/steve/Templates/django/blog/models.py changed, reloading.
2025-04-27 22:26:06,093 - INFO - /home/steve/Templates/django/blog/forms.py changed, reloading.
2025-04-27 22:50:36,247 - INFO - /home/steve/Templates/django/blog/forms.py changed, reloading.
2025-04-27 22:54:58,313 - INFO - /home/steve/Templates/django/blog/forms.py changed, reloading.
2025-04-27 22:59:24,750 - INFO - /home/steve/Templates/django/blog/forms.py changed, reloading.
2025-04-28 00:07:29,239 - ERROR - Internal Server Error: /articles/everything-rumored-for-the-2025-apple-watch-series-11/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: blog_comment.parent_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 66, in article_detail
    return render(request, "blog/article_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 718, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 917, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: blog_comment.parent_id
2025-04-28 00:07:29,343 - WARNING - Not Found: /favicon.ico
2025-04-28 11:25:06,311 - WARNING - Not Found: /favicon.ico
2025-04-28 11:55:14,475 - ERROR - Internal Server Error: /articles/everything-rumored-for-the-2025-apple-watch-series-11/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 70, in article_detail
    return render(request, "blog/article_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'static'. Did you forget to register or load this tag?
2025-04-28 12:11:27,797 - ERROR - Internal Server Error: /articles/everything-rumored-for-the-2025-apple-watch-series-11/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 70, in article_detail
    return render(request, "blog/article_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'static'. Did you forget to register or load this tag?
2025-04-28 14:44:12,405 - ERROR - Internal Server Error: /articles/everything-rumored-for-the-2025-apple-watch-series-11/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 70, in article_detail
    return render(request, "blog/article_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'static'. Did you forget to register or load this tag?
2025-04-28 14:58:01,476 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-28 15:11:17,019 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-28 15:28:25,790 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-28 15:29:00,186 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-28 17:38:25,416 - WARNING - Not Found: /favicon.ico
2025-04-28 18:27:45,207 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-28 19:05:06,995 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 00:32:38,218 - WARNING - Not Found: /favicon.ico
2025-04-29 01:22:18,607 - INFO - /home/steve/Templates/django/blog/models.py changed, reloading.
2025-04-29 02:08:07,037 - INFO - Successfully scraped article ID 214 - URL: https://9to5mac.com/2025/04/24/you-can-get-a-free-apple-watch-pin-today-at-the-apple-store/
2025-04-29 02:08:08,423 - INFO - Successfully scraped article ID 215 - URL: https://9to5mac.com/2025/04/24/apple-tv-has-its-own-spin-on-indiana-jones-and-it-looks-epic/
2025-04-29 02:08:10,083 - INFO - Successfully scraped article ID 216 - URL: https://9to5mac.com/2025/04/24/apple-robotics-ternus-giannandrea/
2025-04-29 02:08:11,514 - INFO - Successfully scraped article ID 217 - URL: https://9to5mac.com/2025/04/24/apple-says-570m-eu-fine-is-unfair-white-house-says-it-wont-be-tolerated/
2025-04-29 02:08:13,008 - INFO - Successfully scraped article ID 218 - URL: https://9to5mac.com/2025/04/24/get-apple-tv-plus-offer-catch-up-tv-recommendations/
2025-04-29 02:08:14,641 - INFO - Successfully scraped article ID 219 - URL: https://9to5mac.com/2025/04/24/apple-launching-15-new-products-later-this-year/
2025-04-29 02:10:56,742 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 24, in home
    return render(request, 'blog/home.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'tag_detail' not found. 'tag_detail' is not a valid view function or pattern name.
2025-04-29 02:17:34,723 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 02:18:07,067 - INFO - /home/steve/Templates/django/blog/urls.py changed, reloading.
2025-04-29 02:18:45,671 - INFO - /home/steve/Templates/django/blog/urls.py changed, reloading.
2025-04-29 02:35:01,787 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 08:34:10,402 - WARNING - Not Found: /favicon.ico
2025-04-29 08:52:58,447 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 09:26:32,394 - INFO - /home/steve/Templates/django/blog/templatetags/custom_filters.py changed, reloading.
2025-04-29 09:29:31,260 - ERROR - Internal Server Error: /articles/apple-explains-how-app-store-reviews-are-summarized-with-ai/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 81, in article_detail
    return render(request, "blog/article_detail.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 701, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 611, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'guess_category'
2025-04-29 09:46:54,558 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 09:58:48,432 - WARNING - Not Found: /path/to/font-awesome/css/font-awesome.min.css
2025-04-29 10:04:12,616 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 11:31:13,513 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 11:31:56,546 - ERROR - Internal Server Error: /articles/everything-rumored-for-the-2025-apple-watch-series-11/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 40, in article_detail
    related_articles = list(related_articles)
                            ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'related_articles' where it is not associated with a value
2025-04-29 11:31:56,627 - WARNING - Not Found: /favicon.ico
2025-04-29 21:40:33,228 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 21:56:49,046 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 21:57:10,134 - INFO - /home/steve/Templates/django/blog/urls.py changed, reloading.
2025-04-29 23:41:53,669 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-04-29 23:44:46,991 - WARNING - Not Found: /favicon.ico
2025-04-30 08:06:58,483 - WARNING - Not Found: /favicon.ico
2025-04-30 12:24:51,923 - WARNING - Not Found: /favicon.ico
2025-04-30 13:46:27,734 - WARNING - Not Found: /articles/pokemon-go-sweet-discoveries-event-guide/
2025-04-30 13:59:48,490 - WARNING - Not Found: /articles/nuevo-iphone-17e-todo-lo-que-creemos-saber-sobre-el-proximo-iphone-asequible-de-apple/
2025-04-30 15:36:42,901 - WARNING - Not Found: /articles/6-first-world-windows-11-problems-i-desperately-want-microsoft-to-fix/
2025-04-30 19:19:34,312 - WARNING - Not Found: /favicon.ico
2025-04-30 19:43:25,815 - WARNING - Not Found: /articles/22-best-macbook-accessories-2025-tested-and-reviewed/
2025-04-30 22:58:09,559 - WARNING - Not Found: /articles/iphone-17-air-almost-as-thin-as-its-buttons-new-images-show/
2025-05-01 02:34:19,602 - WARNING - Not Found: /gcdn/authoring/authoring-images/2025/01/23/USAT/77908224007-xxx-costco-getty-images-1580864430-dcb.jpeg
2025-05-01 02:34:19,608 - WARNING - Not Found: /gcdn/authoring/authoring-images/2025/01/23/USAT/77908242007-gty-2189445660.jpg
2025-05-01 12:34:48,531 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-05-01 14:22:32,844 - ERROR - Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 124, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
                                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 69, in _location
    return self._get("location", item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 39, in _get
    return attr(item)
           ^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 79, in location
    return item.get_absolute_url()
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Article' object has no attribute 'get_absolute_url'
2025-05-01 14:55:45,897 - INFO - /home/steve/Templates/django/blog/models.py changed, reloading.
2025-05-01 14:56:30,406 - INFO - /home/steve/Templates/django/blog/sitemaps.py changed, reloading.
2025-05-01 14:56:52,637 - ERROR - Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sitemap.xml
2025-05-01 15:06:41,264 - INFO - /home/steve/Templates/django/test_project/settings.py changed, reloading.
2025-05-07 17:39:18,299 - ERROR - Invalid HTTP_HOST header: '192.168.59.238:9000'. You may need to add '192.168.59.238' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.59.238:9000'. You may need to add '192.168.59.238' to ALLOWED_HOSTS.
2025-05-07 17:39:18,328 - WARNING - Bad Request: /
2025-05-07 17:39:19,037 - ERROR - Invalid HTTP_HOST header: '192.168.59.238:9000'. You may need to add '192.168.59.238' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.59.238:9000'. You may need to add '192.168.59.238' to ALLOWED_HOSTS.
2025-05-07 17:39:19,056 - WARNING - Bad Request: /favicon.ico
2025-05-07 18:03:25,712 - WARNING - Not Found: /favicon.ico
2025-05-17 20:02:50,967 - WARNING - Not Found: /favicon.ico
2025-05-23 13:50:47,425 - INFO - /home/steve/Templates/django/test_project/settings.py changed, reloading.
2025-05-23 13:59:28,090 - WARNING - Not Found: /favicon.ico
2025-05-23 15:05:01,955 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-05-23 15:13:12,919 - INFO - /home/steve/Templates/django/blog/urls.py changed, reloading.
2025-05-23 15:15:17,504 - ERROR - Internal Server Error: /privacy-policy/
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 173, in privacy_policy
    return render(request, 'blog/privacy_policy.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/backends/django.py", line 109, in render
    reraise(exc, self.backend)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/template/backends/django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
2025-05-25 13:15:17,663 - WARNING - Not Found: /favicon.ico
2025-05-25 14:27:50,035 - INFO - /home/steve/Templates/django/blog/models.py changed, reloading.
2025-05-25 14:29:10,329 - INFO - /home/steve/Templates/django/blog/utils.py changed, reloading.
2025-05-25 14:31:19,282 - INFO - /home/steve/Templates/django/blog/views.py changed, reloading.
2025-05-25 14:31:29,969 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column blog_article.status does not exist
LINE 1: ...T COUNT(*) AS "__count" FROM "blog_article" WHERE "blog_arti...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/Templates/django/blog/views.py", line 21, in home
    page_obj = paginator.get_page(page_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/paginator.py", line 85, in get_page
    return self.page(number)
           ^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/paginator.py", line 110, in count
    return c()
           ^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/sql/query.py", line 630, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/sql/query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: column blog_article.status does not exist
LINE 1: ...T COUNT(*) AS "__count" FROM "blog_article" WHERE "blog_arti...
                                                             ^
